#!/usr/bin/env bash
set -euo pipefail

declare -A LOCAL_PATHS=(
    [vimrc]="$HOME/.vimrc"
    [vim_folder]="$HOME/.vim"
    [zshrc]="$HOME/.zshrc"
    [kitty]="$HOME/.config/kitty/kitty.conf"
    [vscode]="$HOME/.config/Code/User/settings.json"
    [gdbinit]="$HOME/.gdbinit"
)

declare -A REPO_PATHS=(
    [vimrc]="$HOME/dotfiles/vimrc"
    [vim_folder]="$HOME/dotfiles/vim"
    [zshrc]="$HOME/dotfiles/zshrc"
    [kitty]="$HOME/dotfiles/kitty.conf"
    [vscode]="$HOME/dotfiles/settings.json"
    [gdbinit]="$HOME/dotfiles/gdbinit"
)

setup() {
    for key in "${!LOCAL_PATHS[@]}"; do
        local local_path="${LOCAL_PATHS[$key]}"
        local repo_path="${REPO_PATHS[$key]}"
        echo "Installation [$key]: $repo_path -> $local_path"
        mkdir -p "$(dirname "$local_path")"
		rm -rf "$local_path"
        cp -r "$repo_path" "$local_path"
    done
	mkdir -p ~/.config/nvim
	cp ~/.vimrc ~/.config/nvim/init.vim
	cp -r ~/.vim/* ~/.config/nvim/
}

update() {
    for key in "${!LOCAL_PATHS[@]}"; do
        local local_path="${LOCAL_PATHS[$key]}"
        local repo_path="${REPO_PATHS[$key]}"
        echo "Mise à jour [$key]: $local_path -> $repo_path"
        mkdir -p "$(dirname "$repo_path")"
		rm -rf "$repo_path"
        cp -r "$local_path" "$repo_path"
    done
}

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 [setup|update]"
    exit 1
fi

case "$1" in
    setup) setup ;;
    update) update ;;
    *) echo "Commande inconnue: $1" && exit 1 ;;
esac
